pub const CountryData = struct {
    name: []const u8,
    population: u64,
    hasAchievement: bool, // steam limits achievement to 100
};

pub const WORLD_POPULATION = [_]CountryData{
    .{ .name = "World", .population = 8140767120, .hasAchievement = true },
    .{ .name = "India", .population = 1413324000, .hasAchievement = true },
    .{ .name = "China", .population = 1408280000, .hasAchievement = true },
    .{ .name = "United States", .population = 340110988, .hasAchievement = true },
    .{ .name = "Indonesia", .population = 282477584, .hasAchievement = true },
    .{ .name = "Pakistan", .population = 241499431, .hasAchievement = true },
    .{ .name = "Nigeria", .population = 223800000, .hasAchievement = true },
    .{ .name = "Brazil", .population = 212583750, .hasAchievement = true },
    .{ .name = "Bangladesh", .population = 169828911, .hasAchievement = true },
    .{ .name = "Russia", .population = 146028325, .hasAchievement = true },
    .{ .name = "Mexico", .population = 130294079, .hasAchievement = true },
    .{ .name = "Japan", .population = 123400000, .hasAchievement = true },
    .{ .name = "Philippines", .population = 114123600, .hasAchievement = true },
    .{ .name = "Ethiopia", .population = 109499000, .hasAchievement = true },
    .{ .name = "Democratic Republic of the Congo", .population = 109276000, .hasAchievement = true },
    .{ .name = "Egypt", .population = 105914499, .hasAchievement = true },
    .{ .name = "Vietnam", .population = 101343800, .hasAchievement = true },
    .{ .name = "Iran", .population = 85961000, .hasAchievement = true },
    .{ .name = "Turkey", .population = 85664944, .hasAchievement = true },
    .{ .name = "Germany", .population = 83555478, .hasAchievement = true },
    .{ .name = "France", .population = 68620000, .hasAchievement = true },
    .{ .name = "United Kingdom", .population = 68265209, .hasAchievement = true },
    .{ .name = "Thailand", .population = 65932105, .hasAchievement = true },
    .{ .name = "South Africa", .population = 63015904, .hasAchievement = true },
    .{ .name = "Tanzania", .population = 61741120, .hasAchievement = true },
    .{ .name = "Italy", .population = 58924313, .hasAchievement = true },
    .{ .name = "Colombia", .population = 52695952, .hasAchievement = true },
    .{ .name = "Kenya", .population = 52428290, .hasAchievement = true },
    .{ .name = "Myanmar", .population = 51316756, .hasAchievement = true },
    .{ .name = "South Korea", .population = 51183336, .hasAchievement = true },
    .{ .name = "Sudan", .population = 50448963, .hasAchievement = true },
    .{ .name = "Spain", .population = 49077984, .hasAchievement = true },
    .{ .name = "Algeria", .population = 47400000, .hasAchievement = true },
    .{ .name = "Argentina", .population = 47067641, .hasAchievement = true },
    .{ .name = "Uganda", .population = 45905417, .hasAchievement = true },
    .{ .name = "Iraq", .population = 44414800, .hasAchievement = true },
    .{ .name = "Afghanistan", .population = 42045000, .hasAchievement = true },
    .{ .name = "Canada", .population = 41528680, .hasAchievement = true },
    .{ .name = "Uzbekistan", .population = 37697787, .hasAchievement = true },
    .{ .name = "Poland", .population = 37454000, .hasAchievement = true },
    .{ .name = "Morocco", .population = 36828330, .hasAchievement = true },
    .{ .name = "Angola", .population = 35121734, .hasAchievement = true },
    .{ .name = "Malaysia", .population = 34157500, .hasAchievement = true },
    .{ .name = "Peru", .population = 34038457, .hasAchievement = true },
    .{ .name = "Mozambique", .population = 33244414, .hasAchievement = true },
    .{ .name = "Ghana", .population = 33007618, .hasAchievement = true },
    .{ .name = "Ukraine", .population = 32962000, .hasAchievement = true },
    .{ .name = "Yemen", .population = 32305264, .hasAchievement = true },
    .{ .name = "Saudi Arabia", .population = 32175224, .hasAchievement = true },
    .{ .name = "Madagascar", .population = 30811969, .hasAchievement = true },
    .{ .name = "Ivory Coast", .population = 29389150, .hasAchievement = true },
    .{ .name = "Nepal", .population = 29164578, .hasAchievement = true },
    .{ .name = "Cameroon", .population = 28758503, .hasAchievement = true },
    .{ .name = "Venezuela", .population = 28405543, .hasAchievement = true },
    .{ .name = "Australia", .population = 27309396, .hasAchievement = true },
    .{ .name = "Niger", .population = 26312034, .hasAchievement = true },
    .{ .name = "North Korea", .population = 25950000, .hasAchievement = true },
    .{ .name = "Syria", .population = 24672760, .hasAchievement = false },
    .{ .name = "Burkina Faso", .population = 23409015, .hasAchievement = true },
    .{ .name = "Mali", .population = 22395489, .hasAchievement = false },
    .{ .name = "Sri Lanka", .population = 21763170, .hasAchievement = false },
    .{ .name = "Kazakhstan", .population = 20333530, .hasAchievement = true },
    .{ .name = "Malawi", .population = 20270568, .hasAchievement = false },
    .{ .name = "Chile", .population = 20086377, .hasAchievement = false },
    .{ .name = "Zambia", .population = 19610769, .hasAchievement = true },
    .{ .name = "Romania", .population = 19064409, .hasAchievement = false },
    .{ .name = "Somalia", .population = 19009151, .hasAchievement = false },
    .{ .name = "Chad", .population = 18675547, .hasAchievement = true },
    .{ .name = "Senegal", .population = 18126390, .hasAchievement = false },
    .{ .name = "Netherlands", .population = 18066249, .hasAchievement = false },
    .{ .name = "Guatemala", .population = 17843132, .hasAchievement = true },
    .{ .name = "Cambodia", .population = 17336307, .hasAchievement = false },
    .{ .name = "Ecuador", .population = 16938986, .hasAchievement = false },
    .{ .name = "Zimbabwe", .population = 16751469, .hasAchievement = true },
    .{ .name = "South Sudan", .population = 15254268, .hasAchievement = false },
    .{ .name = "Guinea", .population = 14363931, .hasAchievement = false },
    .{ .name = "Rwanda", .population = 13798561, .hasAchievement = true },
    .{ .name = "Benin", .population = 12910087, .hasAchievement = false },
    .{ .name = "Burundi", .population = 12837740, .hasAchievement = false },
    .{ .name = "Tunisia", .population = 11887412, .hasAchievement = true },
    .{ .name = "Haiti", .population = 11867032, .hasAchievement = false },
    .{ .name = "Belgium", .population = 11812354, .hasAchievement = false },
    .{ .name = "Papua New Guinea", .population = 11781559, .hasAchievement = true },
    .{ .name = "Jordan", .population = 11734000, .hasAchievement = false },
    .{ .name = "Bolivia", .population = 11312620, .hasAchievement = false },
    .{ .name = "Cuba", .population = 11089511, .hasAchievement = true },
    .{ .name = "Czech Republic", .population = 10909500, .hasAchievement = false },
    .{ .name = "Dominican Republic", .population = 10771504, .hasAchievement = false },
    .{ .name = "United Arab Emirates", .population = 10678556, .hasAchievement = true },
    .{ .name = "Portugal", .population = 10639726, .hasAchievement = false },
    .{ .name = "Sweden", .population = 10587970, .hasAchievement = false },
    .{ .name = "Greece", .population = 10400720, .hasAchievement = false },
    .{ .name = "Tajikistan", .population = 10277100, .hasAchievement = true },
    .{ .name = "Azerbaijan", .population = 10230666, .hasAchievement = false },
    .{ .name = "Israel", .population = 10045100, .hasAchievement = true },
    .{ .name = "Honduras", .population = 9892632, .hasAchievement = false },
    .{ .name = "Hungary", .population = 9540000, .hasAchievement = false },
    .{ .name = "Austria", .population = 9198214, .hasAchievement = true },
    .{ .name = "Belarus", .population = 9109280, .hasAchievement = false },
    .{ .name = "Switzerland", .population = 9027859, .hasAchievement = false },
    .{ .name = "Sierra Leone", .population = 8884032, .hasAchievement = false },
    .{ .name = "Togo", .population = 8095498, .hasAchievement = true },
    .{ .name = "Laos", .population = 7546000, .hasAchievement = false },
    .{ .name = "Libya", .population = 7381023, .hasAchievement = false },
    .{ .name = "Kyrgyzstan", .population = 7161900, .hasAchievement = true },
    .{ .name = "Turkmenistan", .population = 7057841, .hasAchievement = false },
    .{ .name = "Nicaragua", .population = 6803886, .hasAchievement = false },
    .{ .name = "Serbia", .population = 6605168, .hasAchievement = true },
    .{ .name = "Central African Republic", .population = 6470307, .hasAchievement = false },
    .{ .name = "Bulgaria", .population = 6445481, .hasAchievement = false },
    .{ .name = "Republic of the Congo", .population = 6142180, .hasAchievement = true },
    .{ .name = "Paraguay", .population = 6109644, .hasAchievement = false },
    .{ .name = "Singapore", .population = 6036900, .hasAchievement = false },
    .{ .name = "El Salvador", .population = 6029976, .hasAchievement = false },
    .{ .name = "Denmark", .population = 5992734, .hasAchievement = false },
    .{ .name = "Finland", .population = 5640437, .hasAchievement = true },
    .{ .name = "Norway", .population = 5594340, .hasAchievement = false },
    .{ .name = "Lebanon", .population = 5490000, .hasAchievement = false },
    .{ .name = "Palestine", .population = 5483450, .hasAchievement = false },
    .{ .name = "Slovakia", .population = 5419451, .hasAchievement = true },
    .{ .name = "Ireland", .population = 5380300, .hasAchievement = false },
    .{ .name = "New Zealand", .population = 5356700, .hasAchievement = false },
    .{ .name = "Costa Rica", .population = 5309625, .hasAchievement = false },
    .{ .name = "Oman", .population = 5274249, .hasAchievement = false },
    .{ .name = "Liberia", .population = 5248621, .hasAchievement = false },
    .{ .name = "Mauritania", .population = 4927532, .hasAchievement = true },
    .{ .name = "Kuwait", .population = 4913271, .hasAchievement = false },
    .{ .name = "Panama", .population = 4064780, .hasAchievement = true },
    .{ .name = "Croatia", .population = 3859686, .hasAchievement = false },
    .{ .name = "Georgia", .population = 3694600, .hasAchievement = false },
    .{ .name = "Eritrea", .population = 3535603, .hasAchievement = true },
    .{ .name = "Mongolia", .population = 3504741, .hasAchievement = false },
    .{ .name = "Uruguay", .population = 3499451, .hasAchievement = false },
    .{ .name = "Bosnia and Herzegovina", .population = 3264873, .hasAchievement = true },
    .{ .name = "Armenia", .population = 3075800, .hasAchievement = false },
    .{ .name = "Namibia", .population = 3022401, .hasAchievement = false },
    .{ .name = "Lithuania", .population = 2889402, .hasAchievement = true },
    .{ .name = "Qatar", .population = 2857822, .hasAchievement = false },
    .{ .name = "Jamaica", .population = 2825544, .hasAchievement = false },
    .{ .name = "Moldova", .population = 2423300, .hasAchievement = true },
    .{ .name = "Gambia", .population = 2417471, .hasAchievement = false },
    .{ .name = "Botswana", .population = 2410338, .hasAchievement = false },
    .{ .name = "Gabon", .population = 2408586, .hasAchievement = false },
    .{ .name = "Albania", .population = 2402113, .hasAchievement = false },
    .{ .name = "Lesotho", .population = 2306000, .hasAchievement = true },
    .{ .name = "Slovenia", .population = 2130850, .hasAchievement = false },
    .{ .name = "Latvia", .population = 1848600, .hasAchievement = true },
    .{ .name = "North Macedonia", .population = 1826247, .hasAchievement = false },
    .{ .name = "Guinea-Bissau", .population = 1781308, .hasAchievement = false },
    .{ .name = "Bahrain", .population = 1588670, .hasAchievement = true },
    .{ .name = "Equatorial Guinea", .population = 1558160, .hasAchievement = false },
    .{ .name = "Timor-Leste", .population = 1373024, .hasAchievement = true },
    .{ .name = "Estonia", .population = 1369995, .hasAchievement = false },
    .{ .name = "Trinidad and Tobago", .population = 1368333, .hasAchievement = false },
    .{ .name = "Mauritius", .population = 1244477, .hasAchievement = true },
    .{ .name = "Eswatini", .population = 1235549, .hasAchievement = false },
    .{ .name = "Djibouti", .population = 1066809, .hasAchievement = true },
    .{ .name = "Cyprus", .population = 966400, .hasAchievement = false },
    .{ .name = "Fiji", .population = 900869, .hasAchievement = false },
    .{ .name = "Comoros", .population = 870038, .hasAchievement = false },
    .{ .name = "Bhutan", .population = 777224, .hasAchievement = true },
    .{ .name = "Guyana", .population = 772975, .hasAchievement = false },
    .{ .name = "Solomon Islands", .population = 750325, .hasAchievement = false },
    .{ .name = "Luxembourg", .population = 672050, .hasAchievement = true },
    .{ .name = "Montenegro", .population = 623633, .hasAchievement = false },
    .{ .name = "Suriname", .population = 616500, .hasAchievement = false },
    .{ .name = "Malta", .population = 563443, .hasAchievement = true },
    .{ .name = "Maldives", .population = 515132, .hasAchievement = false },
    .{ .name = "Cape Verde", .population = 491233, .hasAchievement = false },
    .{ .name = "Brunei", .population = 455500, .hasAchievement = true },
    .{ .name = "Belize", .population = 410919, .hasAchievement = false },
    .{ .name = "Bahamas", .population = 398165, .hasAchievement = false },
    .{ .name = "Iceland", .population = 389450, .hasAchievement = false },
    .{ .name = "Vanuatu", .population = 321409, .hasAchievement = true },
    .{ .name = "Barbados", .population = 267800, .hasAchievement = false },
    .{ .name = "Sao Tome and Principe", .population = 228319, .hasAchievement = true },
    .{ .name = "Samoa", .population = 205557, .hasAchievement = false },
    .{ .name = "Saint Lucia", .population = 184100, .hasAchievement = false },
    .{ .name = "Seychelles", .population = 122038, .hasAchievement = true },
    .{ .name = "Kiribati", .population = 120740, .hasAchievement = false },
    .{ .name = "Grenada", .population = 112579, .hasAchievement = false },
    .{ .name = "Saint Vincent and the Grenadines", .population = 110872, .hasAchievement = false },
    .{ .name = "Micronesia", .population = 105754, .hasAchievement = false },
    .{ .name = "Antigua and Barbuda", .population = 103603, .hasAchievement = false },
    .{ .name = "Tonga", .population = 100179, .hasAchievement = false },
    .{ .name = "Andorra", .population = 87663, .hasAchievement = true },
    .{ .name = "Dominica", .population = 67408, .hasAchievement = false },
    .{ .name = "Saint Kitts and Nevis", .population = 51320, .hasAchievement = false },
    .{ .name = "Marshall Islands", .population = 42418, .hasAchievement = true },
    .{ .name = "Liechtenstein", .population = 40900, .hasAchievement = false },
    .{ .name = "Monaco", .population = 38367, .hasAchievement = false },
    .{ .name = "San Marino", .population = 34035, .hasAchievement = false },
    .{ .name = "Palau", .population = 16733, .hasAchievement = true },
    .{ .name = "Nauru", .population = 11680, .hasAchievement = false },
    .{ .name = "Tuvalu", .population = 10643, .hasAchievement = false },
    .{ .name = "Vatican City", .population = 882, .hasAchievement = true },
};
